name: Node Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_on_push:
    runs-on: ubuntu-latest
    steps:
      # This brings source code into current working directory
      - uses: actions/checkout@v2
      # Setup Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      # This is like npm install. But a clean install for ci Server
      - run: npm run client-install
      - run: npm run client-test
      - run: npm run client-build
